### ISSUE TITLE
CSS inlining doesn't work when including image on Laravel 10 and Laravel 9

### ISSUE THREAD

**Issue by bbprojectnet** [fedeisas/laravel-mail-css-inliner#311]
Hi,

In Laravel 10 inliner don't work at all.

After a short look at the code, I came up with what to improve to make it work with Laravel 10:

CssInlinerPlugin.php, line 99:

```
} elseif ($body instanceof AlternativePart || $body instanceof MixedPart) {
```

change to:

```
} elseif ($body instanceof AbstractMultipartPart) {
```

I haven't tested it on a larger scale (e.g. with Laravel 9), I'm posting it as a suggestion.

**Comment by DannyvdSluijs** [comment]
Thanks for reporting the issue @bbprojectnet since you already found a solution do you think you can make a pull request for this?

**Comment by danhanly** [comment]
@bbprojectnet I've created the PR, and included your suggested changes.

When you were working on this, did you get this to work with Laravel 10 by making your suggested change?

**Comment by bbprojectnet** [comment]
> When you were working on this, did you get this to work with Laravel 10 by making your suggested change?

Yes.

> I've created the PR, and included your suggested changes.

Thanks a lot! :)

**Comment by kirkbushell** [comment]
Just to reiterate here that I have it working on Laravel 10 without this change.

**Comment by bbprojectnet** [comment]
What do you mean by working? Yes, there is no error, but in my case inline css was not added.

**Comment by kirkbushell** [comment]
> What do you mean by working? Yes, there is no error, but in my case inline css was not added.

As in, this change isn't necessary for the package to do its thing. I had no issues.

**Comment by DannyvdSluijs** [comment]
Hi @bbprojectnet 

Since time has passed I've learned more about the issues and more often it seems to be a local issue. I've created a small [Laravel10MailCssInliner](https://github.com/DannyvdSluijs/Laravel10MailCssInliner) to show the correct wokring of this package in combination with Laravel 10.

Using the [SendEmail](https://github.com/DannyvdSluijs/Laravel10MailCssInliner/blob/main/app/Console/Commands/SendEmail.php) command (`php artisan app:send-email`) you can check the logs (`storage/logs`) where you can see the inlined version of the css which in the [view](https://github.com/DannyvdSluijs/Laravel10MailCssInliner/blob/main/resources/views/mails/test-email.blade.php) is linked using the `link` tag.

I recommend you take another look into the problems you're facing and see what the differences are compared to the playground. You can always share you problems here and people could volenteer to help you out.

**Comment by bbprojectnet** [comment]
Of course, there are some differences between the example you provided and my code, for example that my email contains both HTML and plain text. I will try to re-examine the matter and point out any differences.

**Comment by bbprojectnet** [comment]
Ok, i figured it out, please add something like this to your `test-email.blade.php`:

```
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/main.css') }}">
</head>
<body>
<h1>Hey you</h1>
<img src="{{ $message->embed(resource_path('logo.png')) }}" />
</body>
</html>
```

result:

![obraz](https://github.com/fedeisas/laravel-mail-css-inliner/assets/1136309/2f6c6929-bbdd-4a60-8716-7ece8a872ccc)

No inline styles.

**Comment by DannyvdSluijs** [comment]
Brilliant this seems to take a different turn in code indeed. @bbprojectnet thanks for the quick and helpful feedback.
In the Playground example the `$body` is a `Symfony\Component\Mime\Part\TextPart` whereas with your addition it changes to a `Symfony\Component\Mime\Part\Multipart\RelatedPart` which is extending the `Symfony\Component\Mime\Part\Multipart\AbstractMultipartPart ` which is indeed the reason why the proposed fix is working.

I can see the `TextPart` is also extending the `AbstractMultipartPart` which makes that I would like to take some time and look into the class hierarchy and see if we can improve the suggested changes. And also take Laravel 9 into account.

**Comment by DannyvdSluijs** [comment]
This has been fixed in https://github.com/fedeisas/laravel-mail-css-inliner/pull/313
